### PR TITLE
Added Firebase Authentication

### PR DESCRIPTION
**Pull request by mihiraggarwal**

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
Please upload GIFs / images demonstrating the features added. 
Thanks for your PR.

**Comment by oorjitchowdhary** [comment]
Also, I seem to find a lot of unknown and redundant files. The ./idea directory should be clean. 

What are these files and why were they added? 

```
com.jetbrains
```

**Comment by mihiraggarwal** [comment]
Screenshot (20)
Firstly I changed a few of the keywords used since they seemed outdated such as compile to implementation. I also made sure not to delete or replace anything from build.gradle so all the ones I wanted to change, I converted them to comments.

**Comment by mihiraggarwal** [comment]
Screenshot (21)
Screenshot (22)
Then I edited the activity_login.xml so as to add the Sign Up button and convert the first EditText to 'typeEmailAddress' since Firebase Authenticaton using Email and Password can only work if the user inputs his/her email address.
I also added the logout button in the activity_menu.xml.

**Comment by mihiraggarwal** [comment]
Screenshot (23)
Screenshot (24)
Screenshot (25)
Finally I edited both the java files to add the respective functions for the implementation of the Firebase namely 'login()', 'signUp()' and 'logout()'. Here also I made sure not to delete any of the pre-existing code that I had to edit and so I converted it all to a comment for the developers' convenience.

**Comment by rachittt** [comment]
@mihiraggarwal instead of explaining us your flow of code, we would appreciate if you put in the GIF showing the Firebase Auth actually working :)

**Comment by mihiraggarwal** [comment]
VID-20190610-WA0012
VID-20190610-WA0014
VID-20190610-WA0013
VID-20190610-WA0004
These GIFs show sign up, login, logout, and error handling.

**Comment by mihiraggarwal** [comment]
Screenshot_2019-06-10-11-21-32-924_com android browser
Also this screenshot shows that the user's details have been added in the Firebase Console

**Comment by rachittt** [comment]
good work!

**Pull request merged**
